// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc.Models;

#nullable disable

namespace mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231101200644_Photopath nullable")]
    partial class Photopathnullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mvc.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "rohit@bcci.com",
                            Name = "Rohit Sharma",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "shubhman@bcci.com",
                            Name = "Shubhman Gill",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "virat@bcci.com",
                            Name = "Virat Kohli",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 4,
                            Department = 1,
                            Email = "shreyas@bcci.com, PhotoPath=\"\" ",
                            Name = "Shreyas Iyyer"
                        },
                        new
                        {
                            Id = 5,
                            Department = 4,
                            Email = "rahul@bcci.com",
                            Name = "KL Rahul",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 6,
                            Department = 1,
                            Email = "surya@bcci.com",
                            Name = "Surya Yadav",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 7,
                            Department = 3,
                            Email = "hardik@bcci.com",
                            Name = "Hardik Pandya",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 8,
                            Department = 3,
                            Email = "jadeja@bcci.com",
                            Name = "Ravi Jadeja",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 9,
                            Department = 2,
                            Email = "kuldeep@bcci.com",
                            Name = "Kuldeep Yadav",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 10,
                            Department = 2,
                            Email = "shami@bcci.com",
                            Name = "Mohd. Shami",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 11,
                            Department = 2,
                            Email = "jasprit@bcci.com",
                            Name = "Jasprit Bumrah",
                            PhotoPath = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
